// Generated by CoffeeScript 1.4.0
(function() {
  var App,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = App = (function() {

    function App() {
      this.nextSlide = __bind(this.nextSlide, this);

      this.loop = __bind(this.loop, this);

      this.timer = __bind(this.timer, this);

      this.keyPress = __bind(this.keyPress, this);
      $(window).keyup(this.keyPress);
      $('section:first-child').show().addClass('active');
      this.playing = false;
      this.seconds = 0;
    }

    App.prototype.keyPress = function(event) {
      if (!this.playing) {
        this.playing = true;
        this.timer();
        return this.loop();
      }
    };

    App.prototype.timer = function() {
      $('#timer').html(this.seconds);
      this.seconds += 1;
      return setTimeout(this.timer, 1000);
    };

    App.prototype.loop = function() {
      this.nextSlide();
      return setTimeout(this.loop, 20000);
    };

    App.prototype.nextSlide = function() {
      var next;
      next = $('.active').next('section');
      if (next.length !== 0) {
        $('.active').hide().removeClass('active');
        return next.show().addClass('active');
      }
    };

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
